image: ruby:2.4

stages:
  - build
  - deploy

build-jekyll:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
  script:
    - bundle install
    - bundle exec jekyll build
  artifacts:
    name: "site-files-$CI_COMMIT_REF_NAME"
    paths:
      - _site
    expire_in: 1 hour

.deploy-jekyll:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  dependencies:
    - build-jekyll

deploy-production:
  extends: .deploy-jekyll
  script:
    - aws s3 cp _site s3://$AWS_S3_BUCKET_PROD/ --recursive
    - aws s3 cp _site/assets/ s3://$AWS_S3_BUCKET_STAGING/assets/ --recursive --cache-control 'public, max-age=86400, must-revalidate'
  only:
    - master

deploy-staging:
  extends: .deploy-jekyll
  script:
    - aws s3 cp _site s3://$AWS_S3_BUCKET_STAGING/ --recursive
    - aws s3 cp _site/assets/ s3://$AWS_S3_BUCKET_STAGING/assets/ --recursive --cache-control 'public, max-age=86400, must-revalidate'
  only:
    - staging
