image: ruby:2.7

stages:
  - build
  - deploy

build-jekyll:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
  script:
    - bundle install
    - bundle exec jekyll build
  artifacts:
    name: "site-files-$CI_COMMIT_REF_NAME"
    paths:
      - _site
    expire_in: 1 hour

.deploy-jekyll:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  dependencies:
    - build-jekyll

deploy-production:
  extends: .deploy-jekyll
  script:
    - AWS_ACCESS_KEY_ID=$AWS_PROD_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_PROD_SECRET_ACCESS_KEY
    - aws s3 sync _site s3://$AWS_PROD_S3_BUCKET/ --delete
    - aws s3 cp _site/assets/ s3://$AWS_PROD_S3_BUCKET/assets/ --recursive --cache-control 'public, max-age=604800, must-revalidate'
  only:
    - master

deploy-staging:
  extends: .deploy-jekyll
  script:
    - AWS_ACCESS_KEY_ID=$AWS_STAGING_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_STAGING_SECRET_ACCESS_KEY
    - aws s3 sync _site s3://$AWS_STAGING_S3_BUCKET/ --delete
    - aws s3 cp _site/assets/ s3://$AWS_STAGING_S3_BUCKET/assets/ --recursive --cache-control 'public, max-age=604800, must-revalidate'
  only:
    - staging
