image: ruby:2.4

stages:
  - build
  - deploy

build-jekyll:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq nodejs
  script:
    - bundle install
    - bundle exec jekyll build
  artifacts:
    name: "site-files-$CI_COMMIT_REF_NAME"
    paths:
      - _site
    expire_in: 1 hour

.deploy-to-s3:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 cp _site s3://$AWS_S3_BUCKET/ --recursive
  dependencies:
    - build-jekyll
