# Site settings
title: Alex Gardner
email: alex@alexgardner.id.au
description: > 
    I am a Linux Systems Administrator, originally from Adelaide and now based in Sydney. In my free time I shoot longbows and generally geek out.
keywords: > 
    alex,gardner,alexgardner,linux,systems,administrator,nix,sysadmin,sydney,syd,adelaide,adl,archer,archery,longbow,longbowman,arrows,fletching,medieval
baseurl: ""
url: "https://alexgardner.id.au"
linkedin_url: https://www.linkedin.com/in/alexandergardner?rel=author
gpgkey: alex-gardner-public-key.asc

# Build settings
markdown: kramdown

gems:
  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass
