title: Alex Gardner
email: alex@alexgardner.id.au
description: > 
  I'm a Linux Systems Administrator, originally from Adelaide and currently living in Sydney. In my free time I shoot longbows and generally geek out.
baseurl: ""
url: "https://alexgardner.id.au"
linkedin_url: https://www.linkedin.com/in/alexandergardner?rel=author
gpgkey: alex-gardner-public-key.asc

# Build settings
markdown: kramdown
#theme: spectral_jekyll_theme
gems:
  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass
