name: Build and Deploy Staging to AWS

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  PublishStaging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ env.SITE_URL }}
    steps:
      - name: Clone the repository to source
        uses: actions/checkout@v3

      - name: Ensure Jekyll site url correctly set
        run: |
          sed -E 's|^url: .*$|url: ${{ env.SITE_URL }}|' -i _config.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: github-deploy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Build Site
        run: bundle exec jekyll build

      - name: Upload to S3
        run: |
          aws s3 sync _site s3://${{ secrets.AWS_S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
